contact_form_action = "#"
custom_script = ""
email = "catarina@tropicalwhitevillages.com"
favicon = "images/favicon.png"
featured_post = true
image_gallery = true
logo = "images/twv.png"
logo_text = "Tropical White Villages"
logo_width = "240x"
mainSections = ["post"]
page_not_found_image = "images/404.png"
announce_image = "images/announce.png"
post_layout = "grid"
search = true
sidebar = "right"
[baidu]
analytics_id = ""
enable = false
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[counter]
enable = false
username = ""
[matomo]
enable = false
id = ""
url = ""
[metadata]
author = "Tropicaldo"
description = "Costa Tropical Property Estate Agents"
image = "images/favicon.png"
keywords = ["IT", "website", "design"]
[plausible]
domain = ""
enable = false
[preloader]
enable = false
preloader = ""
[promotion]
button_label = "Get Started"
button_link = "https://themefisher.com/"
content = "Lorem ipsum dolor sit amet, consectetur sociis. Etiam nunc amet id dignissim. Feugiat id tempor vel sit ornare."
image = "images/promotion.jpg"
title = "Create Stunning Website!!"
[site_verification]
baidu = ""
bing = ""
facebook = ""
google = ""
[snipcart]
currency = "$"
enable = false
snipcart_api = "ZDgxY2ZiM2EtMWRmMi00M2ZkLWI1MDAtNzA2MDc0Y2Q1MzJlNjM3MTAzNDIwOTQ1NDA4NjM4"
[subscription]
enable = true
mailchimp_form_action = ""
mailchimp_form_name = ""
[widgets]
sidebar = ["search", "recent-post", "about-me", "subscription", "tags", "social"]
[[social]]
icon = "fab fa-facebook"
link = "https://www.facebook.com/tropicalwhitevillages/"
name = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "#"
name = "twitter"
[[social]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/tropicalwhitevillages/"
name = "instagram"
